/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/v1/health/live": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Report process liveness only */
        readonly get: operations["getLiveness"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/health/ready": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Report daemon and controller readiness */
        readonly get: operations["getReadiness"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/system": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Report static system facts that do not depend on a session */
        readonly get: operations["getSystem"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/snapshot": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Read the complete immutable machine snapshot */
        readonly get: operations["getMachineSnapshot"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/events": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Stream bounded, resumable daemon events */
        readonly get: operations["streamEvents"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/session/connect": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Verify and connect the configured controller session */
        readonly post: operations["connectSession"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/session/recover": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Run explicitly confirmed fail-closed session recovery */
        readonly post: operations["recoverSession"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/machine/stop": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Request priority software stop
         * @description This is a software stop, not a physical emergency stop. The wildcard generation requests an attempt despite stale or uncertain state and does not imply success.
         */
        readonly post: operations["stopMachine"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/operations/home": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Home the feeder, sorter, or both */
        readonly post: operations["homeMachine"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/operations/sort": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Sort one case to a capability-validated slot */
        readonly post: operations["sortCase"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/operations/feed": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Run one capability-validated feed operation
         * @description The daemon rejects this operation as NOT_READY until the firmware feed lifecycle gate is qualified and the active session advertises support.
         */
        readonly post: operations["feedCase"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/operations": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Read bounded durable operation history */
        readonly get: operations["listOperations"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/operations/{operation_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Read one durable operation */
        readonly get: operations["getOperation"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/configuration": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Read controlled daemon configuration */
        readonly get: operations["getConfiguration"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        /** Apply an allow-listed daemon configuration change */
        readonly patch: operations["updateConfiguration"];
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        readonly ApiVersion: "v1";
        readonly Generation: number;
        /**
         * Format: date-time
         * @description RFC 3339 UTC timestamp.
         */
        readonly Timestamp: string;
        readonly Actor: {
            /** @description Opaque SvelteKit attribution; not a daemon authentication credential. */
            readonly user_id: string;
            /**
             * @description 'machine' (PI-VISION-007, ADR-0013) is the one non-human role: a narrowly-scoped autonomous actor, never a browser session, restricted by the daemon to submitting sort and authenticated with its own distinct service credential - never reachable with the BFF's own credential, and never any other role's, under any configuration.
             * @enum {string}
             */
            readonly role: "viewer" | "operator" | "administrator" | "machine";
        };
        readonly ActorCommand: {
            readonly api_version: components["schemas"]["ApiVersion"];
            readonly actor: components["schemas"]["Actor"];
        };
        readonly RecoverRequest: {
            readonly api_version: components["schemas"]["ApiVersion"];
            readonly actor: components["schemas"]["Actor"];
            /** @constant */
            readonly confirm_uncertain_recovery: true;
        };
        readonly HomeRequest: {
            readonly api_version: components["schemas"]["ApiVersion"];
            readonly actor: components["schemas"]["Actor"];
            /** @enum {string} */
            readonly target: "feeder" | "sorter" | "both";
        };
        readonly SortRequest: {
            readonly api_version: components["schemas"]["ApiVersion"];
            readonly actor: components["schemas"]["Actor"];
            /** @description The active firmware capability snapshot may impose a lower maximum. */
            readonly slot: number;
        };
        /** @enum {string} */
        readonly ConnectionState: "DISCONNECTED" | "CONNECTING" | "VERIFYING_V1" | "ACTIVATING_V2" | "READY" | "RECOVERING" | "UNCERTAIN";
        /** @enum {string} */
        readonly FaultState: "CLEAR" | "ACTIVE" | "LATCHED" | "UNCERTAIN";
        /** @enum {string} */
        readonly OperationState: "QUEUED" | "ACCEPTED" | "RUNNING" | "SUCCEEDED" | "FAILED" | "CANCELLED" | "UNCERTAIN";
        /** @enum {string} */
        readonly OperationType: "CONNECT" | "RECOVER" | "STOP" | "HOME" | "SORT" | "FEED" | "CONFIGURE";
        /** @enum {string} */
        readonly OperationOutcome: "COMPLETED" | "STOPPED" | "FAILED" | "CANCELLED" | "UNCERTAIN";
        readonly OperationAccepted: {
            readonly api_version: components["schemas"]["ApiVersion"];
            /**
             * Format: uuid
             * @description Durable daemon identity; never a firmware protocol request_id.
             */
            readonly operation_id: string;
            readonly state: components["schemas"]["OperationState"];
            readonly generation: components["schemas"]["Generation"];
            readonly accepted_at: components["schemas"]["Timestamp"];
            readonly status_url: string;
        };
        readonly Operation: {
            readonly api_version: components["schemas"]["ApiVersion"];
            /** Format: uuid */
            readonly operation_id: string;
            readonly type: components["schemas"]["OperationType"];
            readonly state: components["schemas"]["OperationState"];
            readonly actor: components["schemas"]["Actor"];
            readonly created_at: components["schemas"]["Timestamp"];
            readonly deadline_at: components["schemas"]["Timestamp"];
            readonly generation: components["schemas"]["Generation"];
            /** @description True only after a trusted correlated firmware terminal. SUCCEEDED requires true. */
            readonly trusted_terminal: boolean;
            /** @description Protocol fields carried by the trusted terminal response, if any (e.g. the sorted slot for a SUCCEEDED sort operation). Bounded by the daemon; never raw unbounded serial content. */
            readonly terminal_fields?: {
                readonly [key: string]: string;
            };
            readonly started_at?: components["schemas"]["Timestamp"];
            readonly terminal_at?: components["schemas"]["Timestamp"];
            readonly outcome?: components["schemas"]["OperationOutcome"];
            readonly error?: components["schemas"]["OperationError"];
        } & (unknown & unknown);
        readonly OperationError: {
            readonly code: components["schemas"]["ErrorCode"];
            readonly message: string;
        };
        readonly OperationPage: {
            readonly api_version: components["schemas"]["ApiVersion"];
            readonly items: readonly components["schemas"]["Operation"][];
            readonly next_cursor?: string | null;
        };
        readonly Capabilities: {
            readonly v2_available: boolean;
            readonly crc_active: boolean;
            readonly slot_count: number;
            readonly home_available: boolean;
            readonly sort_available: boolean;
            readonly feed_available: boolean;
            readonly feed_unavailable_reason?: string;
        };
        readonly FirmwareState: {
            readonly firmware_version?: string | null;
            /**
             * @description Negotiated firmware protocol version, independent of daemon API v1.
             * @enum {integer}
             */
            readonly protocol_version: 1 | 2;
            readonly capabilities: components["schemas"]["Capabilities"];
        };
        readonly MachineState: {
            readonly feed_homed: boolean;
            readonly sort_homed: boolean;
            readonly sorter_slot?: number | null;
        };
        readonly Fault: {
            /** Format: uuid */
            readonly fault_id: string;
            readonly state: components["schemas"]["FaultState"];
            readonly code: string;
            /** @enum {string} */
            readonly source: "daemon" | "journal" | "transport" | "protocol" | "firmware";
            readonly message?: string;
            readonly opened_at: components["schemas"]["Timestamp"];
        };
        readonly MachineSnapshot: {
            readonly api_version: components["schemas"]["ApiVersion"];
            readonly generation: components["schemas"]["Generation"];
            readonly connection_state: components["schemas"]["ConnectionState"];
            readonly fault_state: components["schemas"]["FaultState"];
            /** @description Verified daemon/session readiness only; not physical safety or homing. */
            readonly ready: boolean;
            readonly readiness_reason?: string | null;
            readonly active_operation?: components["schemas"]["Operation"] | null;
            readonly firmware: components["schemas"]["FirmwareState"];
            readonly machine: components["schemas"]["MachineState"];
            readonly faults: readonly components["schemas"]["Fault"][];
            readonly observed_at: components["schemas"]["Timestamp"];
        };
        readonly Liveness: {
            readonly api_version: components["schemas"]["ApiVersion"];
            /** @constant */
            readonly live: true;
            readonly observed_at: components["schemas"]["Timestamp"];
        };
        readonly Readiness: {
            readonly api_version: components["schemas"]["ApiVersion"];
            readonly ready: boolean;
            readonly reason?: string | null;
            readonly connection_state: components["schemas"]["ConnectionState"];
            readonly fault_state: components["schemas"]["FaultState"];
            readonly generation: components["schemas"]["Generation"];
            readonly observed_at: components["schemas"]["Timestamp"];
        };
        readonly System: {
            readonly api_version: components["schemas"]["ApiVersion"];
            /** @description A project evidence-status label (see docs/architecture/README.md's status legend), e.g. NOT_EXECUTED. Never implies the gate passed. */
            readonly dtr_gate_status: string;
            readonly observed_at: components["schemas"]["Timestamp"];
        };
        /** @description Extensible v1 event name. Consumers ignore unknown names and reconcile from snapshots when required. */
        readonly DaemonEventType: string;
        readonly DaemonEvent: {
            readonly api_version: components["schemas"]["ApiVersion"];
            /** @description Monotonic daemon SSE cursor; not a protocol request_id. */
            readonly event_id: number;
            readonly occurred_at: components["schemas"]["Timestamp"];
            readonly generation: components["schemas"]["Generation"];
            readonly type: components["schemas"]["DaemonEventType"];
            /** Format: uuid */
            readonly operation_id?: string;
            /** @description Bounded event-type-specific payload. Consumers ignore unknown fields and event types within API v1. */
            readonly data: {
                readonly [key: string]: unknown;
            };
        };
        readonly ConfigurationValues: {
            readonly heartbeat_interval_ms: number;
            readonly event_retention_count: number;
            readonly operation_retention_days: number;
            readonly max_deadline_ms: number;
        };
        readonly Configuration: {
            readonly api_version: components["schemas"]["ApiVersion"];
            readonly generation: components["schemas"]["Generation"];
            readonly values: components["schemas"]["ConfigurationValues"];
            readonly updated_at: components["schemas"]["Timestamp"];
        };
        readonly ConfigurationPatch: {
            readonly api_version: components["schemas"]["ApiVersion"];
            readonly actor: components["schemas"]["Actor"];
            readonly changes: {
                readonly heartbeat_interval_ms?: number;
                readonly event_retention_count?: number;
                readonly operation_retention_days?: number;
                readonly max_deadline_ms?: number;
            };
        };
        /** @enum {string} */
        readonly ErrorCode: "VALIDATION_FAILED" | "UNAUTHENTICATED" | "FORBIDDEN" | "RESOURCE_NOT_FOUND" | "STALE_GENERATION" | "IDEMPOTENCY_CONFLICT" | "NOT_READY" | "UNCERTAIN" | "QUEUE_FULL" | "DEADLINE_INVALID" | "DEADLINE_EXPIRED" | "JOURNAL_UNAVAILABLE" | "SERVICE_UNAVAILABLE" | "INTERNAL_ERROR";
        readonly Error: {
            readonly api_version: components["schemas"]["ApiVersion"];
            readonly code: components["schemas"]["ErrorCode"];
            readonly message: string;
            /**
             * Format: uuid
             * @description Daemon HTTP diagnostic request identifier, not a firmware protocol request_id.
             */
            readonly request_id: string;
            readonly generation?: components["schemas"]["Generation"];
            /** @description Sanitized bounded details; secrets, arbitrary protocol payloads, and raw serial data are forbidden. */
            readonly details?: {
                readonly [key: string]: unknown;
            };
        };
        readonly ValidationError: components["schemas"]["Error"] & {
            /** @enum {unknown} */
            readonly code?: "VALIDATION_FAILED" | "DEADLINE_INVALID";
        };
        readonly UnauthenticatedError: components["schemas"]["Error"] & {
            /** @constant */
            readonly code?: "UNAUTHENTICATED";
        };
        readonly ForbiddenError: components["schemas"]["Error"] & {
            /** @constant */
            readonly code?: "FORBIDDEN";
        };
        readonly NotFoundError: components["schemas"]["Error"] & {
            /** @constant */
            readonly code?: "RESOURCE_NOT_FOUND";
        };
        readonly DeadlineExpiredError: components["schemas"]["Error"] & {
            /** @constant */
            readonly code?: "DEADLINE_EXPIRED";
        };
        readonly ConflictError: components["schemas"]["Error"] & {
            /** @enum {unknown} */
            readonly code?: "STALE_GENERATION" | "IDEMPOTENCY_CONFLICT" | "NOT_READY" | "UNCERTAIN";
        };
        readonly QueueFullError: components["schemas"]["Error"] & {
            /** @constant */
            readonly code?: "QUEUE_FULL";
        };
        readonly InternalError: components["schemas"]["Error"] & {
            /** @constant */
            readonly code?: "INTERNAL_ERROR";
        };
        readonly UnavailableError: components["schemas"]["Error"] & {
            /** @enum {unknown} */
            readonly code?: "JOURNAL_UNAVAILABLE" | "SERVICE_UNAVAILABLE";
        };
    };
    responses: {
        /** @description Durably admitted or deduplicated operation. Firmware completion is not implied. */
        readonly OperationAccepted: {
            headers: {
                readonly "X-Request-ID": components["headers"]["XRequestId"];
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["OperationAccepted"];
            };
        };
        /** @description VALIDATION_FAILED or DEADLINE_INVALID. */
        readonly ValidationFailed: {
            headers: {
                readonly "X-Request-ID": components["headers"]["XRequestId"];
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/problem+json": components["schemas"]["ValidationError"];
            };
        };
        /** @description UNAUTHENTICATED. */
        readonly Unauthenticated: {
            headers: {
                readonly "X-Request-ID": components["headers"]["XRequestId"];
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/problem+json": components["schemas"]["UnauthenticatedError"];
            };
        };
        /** @description FORBIDDEN. */
        readonly Forbidden: {
            headers: {
                readonly "X-Request-ID": components["headers"]["XRequestId"];
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/problem+json": components["schemas"]["ForbiddenError"];
            };
        };
        /** @description RESOURCE_NOT_FOUND. */
        readonly NotFound: {
            headers: {
                readonly "X-Request-ID": components["headers"]["XRequestId"];
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/problem+json": components["schemas"]["NotFoundError"];
            };
        };
        /** @description DEADLINE_EXPIRED. */
        readonly DeadlineExpired: {
            headers: {
                readonly "X-Request-ID": components["headers"]["XRequestId"];
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/problem+json": components["schemas"]["DeadlineExpiredError"];
            };
        };
        /** @description STALE_GENERATION, IDEMPOTENCY_CONFLICT, NOT_READY, or UNCERTAIN. */
        readonly Conflict: {
            headers: {
                readonly "X-Request-ID": components["headers"]["XRequestId"];
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/problem+json": components["schemas"]["ConflictError"];
            };
        };
        /** @description QUEUE_FULL. */
        readonly QueueFull: {
            headers: {
                readonly "X-Request-ID": components["headers"]["XRequestId"];
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/problem+json": components["schemas"]["QueueFullError"];
            };
        };
        /** @description Sanitized INTERNAL_ERROR. No machine success is implied. */
        readonly InternalError: {
            headers: {
                readonly "X-Request-ID": components["headers"]["XRequestId"];
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/problem+json": components["schemas"]["InternalError"];
            };
        };
        /** @description JOURNAL_UNAVAILABLE or SERVICE_UNAVAILABLE. */
        readonly ServiceUnavailable: {
            headers: {
                readonly "X-Request-ID": components["headers"]["XRequestId"];
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/problem+json": components["schemas"]["UnavailableError"];
            };
        };
    };
    parameters: {
        /** @description Opaque key scoped to the authenticated BFF identity. Same key and canonical request returns the original result; different content conflicts. */
        readonly IdempotencyKey: string;
        /** @description Exact snapshot generation observed by the caller. */
        readonly IfMatchGeneration: string;
        /** @description Exact observed generation or * to request a priority stop attempt despite stale or uncertain state. */
        readonly StopIfMatchGeneration: string;
        /** @description Finite remaining execution budget in milliseconds when cs71d receives the request. Daemon policy may impose a lower operation-specific maximum. */
        readonly DeadlineMs: number;
        /** @description Last applied daemon event_id. It is unrelated to a firmware protocol request_id. */
        readonly LastEventId: string;
        /** @description Durable daemon operation identifier, never a firmware protocol request_id. */
        readonly OperationId: string;
    };
    requestBodies: {
        readonly ActorCommand: {
            readonly content: {
                readonly "application/json": components["schemas"]["ActorCommand"];
            };
        };
    };
    headers: {
        /** @description Opaque daemon HTTP request correlation identifier for diagnostics. */
        readonly XRequestId: string;
        /** @description Quoted immutable snapshot generation in the form "generation:<n>". */
        readonly GenerationEtag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly getLiveness: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description The daemon process is live; controller readiness is not implied. */
            readonly 200: {
                headers: {
                    readonly "X-Request-ID": components["headers"]["XRequestId"];
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Liveness"];
                };
            };
            readonly 401: components["responses"]["Unauthenticated"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly getReadiness: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Current readiness state. A false ready value is still a successful health read. */
            readonly 200: {
                headers: {
                    readonly "X-Request-ID": components["headers"]["XRequestId"];
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Readiness"];
                };
            };
            readonly 401: components["responses"]["Unauthenticated"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly getSystem: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Current system facts. A NOT_EXECUTED gate is a successful read, not a failure. */
            readonly 200: {
                headers: {
                    readonly "X-Request-ID": components["headers"]["XRequestId"];
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["System"];
                };
            };
            readonly 401: components["responses"]["Unauthenticated"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly getMachineSnapshot: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Complete snapshot for reconciliation. */
            readonly 200: {
                headers: {
                    readonly "X-Request-ID": components["headers"]["XRequestId"];
                    readonly ETag: components["headers"]["GenerationEtag"];
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["MachineSnapshot"];
                };
            };
            readonly 401: components["responses"]["Unauthenticated"];
            readonly 500: components["responses"]["InternalError"];
            readonly 503: components["responses"]["ServiceUnavailable"];
        };
    };
    readonly streamEvents: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: {
                /** @description Last applied daemon event_id. It is unrelated to a firmware protocol request_id. */
                readonly "Last-Event-ID"?: components["parameters"]["LastEventId"];
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description SSE stream. A stale cursor receives snapshot.required before the stream closes. */
            readonly 200: {
                headers: {
                    readonly "X-Request-ID": components["headers"]["XRequestId"];
                    /** @description SSE responses are not cached. */
                    readonly "Cache-Control"?: "no-store";
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "text/event-stream": string;
                };
            };
            readonly 400: components["responses"]["ValidationFailed"];
            readonly 401: components["responses"]["Unauthenticated"];
            readonly 500: components["responses"]["InternalError"];
            readonly 503: components["responses"]["ServiceUnavailable"];
        };
    };
    readonly connectSession: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description Opaque key scoped to the authenticated BFF identity. Same key and canonical request returns the original result; different content conflicts. */
                readonly "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Exact snapshot generation observed by the caller. */
                readonly "If-Match-Generation": components["parameters"]["IfMatchGeneration"];
                /** @description Finite remaining execution budget in milliseconds when cs71d receives the request. Daemon policy may impose a lower operation-specific maximum. */
                readonly "X-Deadline-Ms": components["parameters"]["DeadlineMs"];
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: components["requestBodies"]["ActorCommand"];
        readonly responses: {
            readonly 202: components["responses"]["OperationAccepted"];
            readonly 400: components["responses"]["ValidationFailed"];
            readonly 401: components["responses"]["Unauthenticated"];
            readonly 403: components["responses"]["Forbidden"];
            readonly 408: components["responses"]["DeadlineExpired"];
            readonly 409: components["responses"]["Conflict"];
            readonly 429: components["responses"]["QueueFull"];
            readonly 500: components["responses"]["InternalError"];
            readonly 503: components["responses"]["ServiceUnavailable"];
        };
    };
    readonly recoverSession: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description Opaque key scoped to the authenticated BFF identity. Same key and canonical request returns the original result; different content conflicts. */
                readonly "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Exact snapshot generation observed by the caller. */
                readonly "If-Match-Generation": components["parameters"]["IfMatchGeneration"];
                /** @description Finite remaining execution budget in milliseconds when cs71d receives the request. Daemon policy may impose a lower operation-specific maximum. */
                readonly "X-Deadline-Ms": components["parameters"]["DeadlineMs"];
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["RecoverRequest"];
            };
        };
        readonly responses: {
            readonly 202: components["responses"]["OperationAccepted"];
            readonly 400: components["responses"]["ValidationFailed"];
            readonly 401: components["responses"]["Unauthenticated"];
            readonly 403: components["responses"]["Forbidden"];
            readonly 408: components["responses"]["DeadlineExpired"];
            readonly 409: components["responses"]["Conflict"];
            readonly 429: components["responses"]["QueueFull"];
            readonly 500: components["responses"]["InternalError"];
            readonly 503: components["responses"]["ServiceUnavailable"];
        };
    };
    readonly stopMachine: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description Opaque key scoped to the authenticated BFF identity. Same key and canonical request returns the original result; different content conflicts. */
                readonly "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Exact observed generation or * to request a priority stop attempt despite stale or uncertain state. */
                readonly "If-Match-Generation": components["parameters"]["StopIfMatchGeneration"];
                /** @description Finite remaining execution budget in milliseconds when cs71d receives the request. Daemon policy may impose a lower operation-specific maximum. */
                readonly "X-Deadline-Ms": components["parameters"]["DeadlineMs"];
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: components["requestBodies"]["ActorCommand"];
        readonly responses: {
            readonly 202: components["responses"]["OperationAccepted"];
            readonly 400: components["responses"]["ValidationFailed"];
            readonly 401: components["responses"]["Unauthenticated"];
            readonly 403: components["responses"]["Forbidden"];
            readonly 408: components["responses"]["DeadlineExpired"];
            readonly 409: components["responses"]["Conflict"];
            readonly 429: components["responses"]["QueueFull"];
            readonly 500: components["responses"]["InternalError"];
            readonly 503: components["responses"]["ServiceUnavailable"];
        };
    };
    readonly homeMachine: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description Opaque key scoped to the authenticated BFF identity. Same key and canonical request returns the original result; different content conflicts. */
                readonly "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Exact snapshot generation observed by the caller. */
                readonly "If-Match-Generation": components["parameters"]["IfMatchGeneration"];
                /** @description Finite remaining execution budget in milliseconds when cs71d receives the request. Daemon policy may impose a lower operation-specific maximum. */
                readonly "X-Deadline-Ms": components["parameters"]["DeadlineMs"];
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["HomeRequest"];
            };
        };
        readonly responses: {
            readonly 202: components["responses"]["OperationAccepted"];
            readonly 400: components["responses"]["ValidationFailed"];
            readonly 401: components["responses"]["Unauthenticated"];
            readonly 403: components["responses"]["Forbidden"];
            readonly 408: components["responses"]["DeadlineExpired"];
            readonly 409: components["responses"]["Conflict"];
            readonly 429: components["responses"]["QueueFull"];
            readonly 500: components["responses"]["InternalError"];
            readonly 503: components["responses"]["ServiceUnavailable"];
        };
    };
    readonly sortCase: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description Opaque key scoped to the authenticated BFF identity. Same key and canonical request returns the original result; different content conflicts. */
                readonly "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Exact snapshot generation observed by the caller. */
                readonly "If-Match-Generation": components["parameters"]["IfMatchGeneration"];
                /** @description Finite remaining execution budget in milliseconds when cs71d receives the request. Daemon policy may impose a lower operation-specific maximum. */
                readonly "X-Deadline-Ms": components["parameters"]["DeadlineMs"];
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["SortRequest"];
            };
        };
        readonly responses: {
            readonly 202: components["responses"]["OperationAccepted"];
            readonly 400: components["responses"]["ValidationFailed"];
            readonly 401: components["responses"]["Unauthenticated"];
            readonly 403: components["responses"]["Forbidden"];
            readonly 408: components["responses"]["DeadlineExpired"];
            readonly 409: components["responses"]["Conflict"];
            readonly 429: components["responses"]["QueueFull"];
            readonly 500: components["responses"]["InternalError"];
            readonly 503: components["responses"]["ServiceUnavailable"];
        };
    };
    readonly feedCase: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description Opaque key scoped to the authenticated BFF identity. Same key and canonical request returns the original result; different content conflicts. */
                readonly "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Exact snapshot generation observed by the caller. */
                readonly "If-Match-Generation": components["parameters"]["IfMatchGeneration"];
                /** @description Finite remaining execution budget in milliseconds when cs71d receives the request. Daemon policy may impose a lower operation-specific maximum. */
                readonly "X-Deadline-Ms": components["parameters"]["DeadlineMs"];
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: components["requestBodies"]["ActorCommand"];
        readonly responses: {
            readonly 202: components["responses"]["OperationAccepted"];
            readonly 400: components["responses"]["ValidationFailed"];
            readonly 401: components["responses"]["Unauthenticated"];
            readonly 403: components["responses"]["Forbidden"];
            readonly 408: components["responses"]["DeadlineExpired"];
            readonly 409: components["responses"]["Conflict"];
            readonly 429: components["responses"]["QueueFull"];
            readonly 500: components["responses"]["InternalError"];
            readonly 503: components["responses"]["ServiceUnavailable"];
        };
    };
    readonly listOperations: {
        readonly parameters: {
            readonly query?: {
                readonly state?: components["schemas"]["OperationState"];
                readonly type?: components["schemas"]["OperationType"];
                readonly limit?: number;
                readonly cursor?: string;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description A bounded page of operations ordered newest first. */
            readonly 200: {
                headers: {
                    readonly "X-Request-ID": components["headers"]["XRequestId"];
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["OperationPage"];
                };
            };
            readonly 400: components["responses"]["ValidationFailed"];
            readonly 401: components["responses"]["Unauthenticated"];
            readonly 500: components["responses"]["InternalError"];
            readonly 503: components["responses"]["ServiceUnavailable"];
        };
    };
    readonly getOperation: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                /** @description Durable daemon operation identifier, never a firmware protocol request_id. */
                readonly operation_id: components["parameters"]["OperationId"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Current durable operation state. */
            readonly 200: {
                headers: {
                    readonly "X-Request-ID": components["headers"]["XRequestId"];
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Operation"];
                };
            };
            readonly 400: components["responses"]["ValidationFailed"];
            readonly 401: components["responses"]["Unauthenticated"];
            readonly 404: components["responses"]["NotFound"];
            readonly 500: components["responses"]["InternalError"];
            readonly 503: components["responses"]["ServiceUnavailable"];
        };
    };
    readonly getConfiguration: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Current configuration and snapshot generation. */
            readonly 200: {
                headers: {
                    readonly "X-Request-ID": components["headers"]["XRequestId"];
                    readonly ETag: components["headers"]["GenerationEtag"];
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Configuration"];
                };
            };
            readonly 401: components["responses"]["Unauthenticated"];
            readonly 403: components["responses"]["Forbidden"];
            readonly 500: components["responses"]["InternalError"];
            readonly 503: components["responses"]["ServiceUnavailable"];
        };
    };
    readonly updateConfiguration: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description Opaque key scoped to the authenticated BFF identity. Same key and canonical request returns the original result; different content conflicts. */
                readonly "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Exact snapshot generation observed by the caller. */
                readonly "If-Match-Generation": components["parameters"]["IfMatchGeneration"];
                /** @description Finite remaining execution budget in milliseconds when cs71d receives the request. Daemon policy may impose a lower operation-specific maximum. */
                readonly "X-Deadline-Ms": components["parameters"]["DeadlineMs"];
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["ConfigurationPatch"];
            };
        };
        readonly responses: {
            readonly 202: components["responses"]["OperationAccepted"];
            readonly 400: components["responses"]["ValidationFailed"];
            readonly 401: components["responses"]["Unauthenticated"];
            readonly 403: components["responses"]["Forbidden"];
            readonly 408: components["responses"]["DeadlineExpired"];
            readonly 409: components["responses"]["Conflict"];
            readonly 500: components["responses"]["InternalError"];
            readonly 503: components["responses"]["ServiceUnavailable"];
        };
    };
}
